### PR TITLE
Update sig-storage meetings details

### PR DESCRIPTION
**Pull request by gfidente**
Updates chairs and slot for the sig-storage meeting.

### CODE REVIEW

**Review by nixpanic — APPROVED** [review]
Thanks for the update!

**Comment by nixpanic** [comment]
@rbowen is this something you can merge?

**Comment by rbowen** [comment]
centos.org Git is now at https://git.centos.org/centos/centos.org

**Comment by gfidente** [comment]
@rbowen @arrfab I don't see the Calendar repo there yet though?

**Comment by gfidente** [comment]
thanks for merging this @rbowen !

@fmount @nixpanic would be nice to add a link to some hackmd page with the meetings agenda later in time

**Comment by fmount** [comment]
@gfidente ack, thanks for this commit!

**Pull request merged**
