### PR TITLE
Change time to 13:00 UTC Tue for SCLo SIG

### PR DESCRIPTION
**Pull request by hhorak**
Change time to 13:00 UTC for SCLo SIG, based on https://lists.centos.org/pipermail/centos-devel/2016-May/014743.html

### CODE REVIEW

**Comment by hhorak** [comment]
@bexelbie not sure if you're right person to ping :)

**Comment by bexelbie** [comment]
@hhorak I am ... not sure why I didn't get an email on this.  Merging

**Comment by hhorak** [comment]
Thanks! will the page https://www.centos.org/community/calendar/ be re-generated automatically somehow?

**Comment by bexelbie** [comment]
Yes, the commit I made to that repo is supposed to trigger a rebuild.  I am told to give it at least an hour.

**Pull request merged**
